services:
  mail:
    image: mailhog/mailhog:latest
    ports: 
      - "1025:8025"
  web:
    image: nginx:latest
    build: .
    volumes:
        - ./config/default.conf:/etc/nginx/conf.d/default.conf
        - ./shared-folder:/usr/share/nginx/html
        - ./gallery:/usr/share/nginx/galleryImages
    ports:
        - 80:80
